# Generated by Django 4.1.4 on 2023-01-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profession_statistic_delete_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sity_salary', models.CharField(max_length=35, verbose_name='Город')),
                ('salary', models.CharField(max_length=8, verbose_name='Уровень зарплат')),
                ('sity_percentage', models.CharField(max_length=35, verbose_name='Город')),
                ('percentage', models.CharField(max_length=8, verbose_name='Доля вакансий')),
            ],
            options={
                'verbose_name': 'Статистика по городам',
                'verbose_name_plural': 'Статистики по городам',
            },
        ),
    ]
