# Generated by Django 4.1.4 on 2023-01-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_statisticbyyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='PercentageByCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sity', models.CharField(max_length=35, verbose_name='Город')),
                ('percentage', models.CharField(max_length=8, verbose_name='Доля вакансий')),
            ],
            options={
                'verbose_name': 'Процент вакансий по городам',
                'verbose_name_plural': 'Проценты вакансий по городам',
            },
        ),
        migrations.CreateModel(
            name='SalaryByCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sity', models.CharField(max_length=35, verbose_name='Город')),
                ('salary', models.CharField(max_length=8, verbose_name='Уровень зарплат')),
            ],
            options={
                'verbose_name': 'Статистика зарплаты по городам',
                'verbose_name_plural': 'Статистики зарплат по городам',
            },
        ),
        migrations.DeleteModel(
            name='StatisticByYear',
        ),
    ]
