# Generated by Django 4.1.4 on 2023-01-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_percentagebycity_salarybycity_delete_statisticbyyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('top_skills', models.TextField(verbose_name='Навыки')),
            ],
            options={
                'verbose_name': 'Топ10 вакансий по году',
                'verbose_name_plural': 'Топ10 вакансий по годам',
            },
        ),
    ]
