# Generated by Django 4.1.4 on 2023-01-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_skillsbyyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopSkills2015',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=30, verbose_name='Навык')),
                ('count', models.CharField(max_length=150, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Топ-10 навыков за 2015 год',
                'verbose_name_plural': 'Топ-10 навыков за 2015 год',
            },
        ),
        migrations.CreateModel(
            name='TopSkills2016',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=30, verbose_name='Навык')),
                ('count', models.CharField(max_length=150, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Топ-10 навыков за 2016 год',
                'verbose_name_plural': 'Топ-10 навыков за 2016 год',
            },
        ),
        migrations.CreateModel(
            name='TopSkills2017',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=30, verbose_name='Навык')),
                ('count', models.CharField(max_length=150, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Топ-10 навыков за 2017 год',
                'verbose_name_plural': 'Топ-10 навыков за 2017 год',
            },
        ),
        migrations.CreateModel(
            name='TopSkills2018',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=30, verbose_name='Навык')),
                ('count', models.CharField(max_length=150, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Топ-10 навыков за 2018 год',
                'verbose_name_plural': 'Топ-10 навыков за 2018 год',
            },
        ),
        migrations.CreateModel(
            name='TopSkills2019',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=30, verbose_name='Навык')),
                ('count', models.CharField(max_length=150, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Топ-10 навыков за 2019 год',
                'verbose_name_plural': 'Топ-10 навыков за 2019 год',
            },
        ),
        migrations.CreateModel(
            name='TopSkills2020',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=30, verbose_name='Навык')),
                ('count', models.CharField(max_length=150, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Топ-10 навыков за 2020 год',
                'verbose_name_plural': 'Топ-10 навыков за 2020 год',
            },
        ),
        migrations.CreateModel(
            name='TopSkills2021',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=30, verbose_name='Навык')),
                ('count', models.CharField(max_length=150, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Топ-10 навыков за 2021 год',
                'verbose_name_plural': 'Топ-10 навыков за 2021 год',
            },
        ),
        migrations.CreateModel(
            name='TopSkills2022',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=30, verbose_name='Навык')),
                ('count', models.CharField(max_length=150, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Топ-10 навыков за 2022 год',
                'verbose_name_plural': 'Топ-10 навыков за 2022 год',
            },
        ),
    ]
