# Generated by Django 4.1.4 on 2023-01-14 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_topskills2015_topskills2016_topskills2017_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkillsByYear',
        ),
    ]
